import { calendar_month, weekday_row } from "../types/calendar-types.slint";
import { CalendarView } from "../components/calendar-view.slint";

export component CalendarPage inherits Rectangle {
    in property <calendar_month> month_data;
    in property <weekday_row> weekdays;

    callback prev_month();
    callback next_month();
    callback go_today();
    callback day_clicked(int, int, int);

    CalendarView {
        month_data: root.month_data;
        weekdays: root.weekdays;

        prev_month => { root.prev_month(); }
        next_month => { root.next_month(); }
        go_today => { root.go_today(); }
        day_clicked(year, month, day) => { root.day_clicked(year, month, day); }
    }
}
