import { FluentTokens } from "../../theme/fluent-tokens.slint";

export component Button inherits Rectangle {
    callback clicked();

    out property <bool> pressed: touch.pressed;
    out property <bool> has-hover: touch.has-hover;

    border-radius: FluentTokens.border_radius_small;
    background: touch.pressed ? FluentTokens.neutral_bg_1_pressed
        : touch.has-hover ? FluentTokens.neutral_bg_1_hover
        : FluentTokens.neutral_bg_1;

    touch := TouchArea {
        clicked => { root.clicked(); }
        mouse-cursor: pointer;
    }

    animate background { duration: FluentTokens.duration_fast; easing: FluentTokens.curve_easy_ease; }

    accessible-role: button;
}
