import { FluentTokens } from "../../theme/fluent-tokens.slint";
import { Button } from "./button.slint";

export component IconButton inherits Button {
    in property <length> icon_size: 28px;
    in property <image> icon;
    in property <string> label;

    width: icon_size;
    height: icon_size;

    Image {
        source: icon;
        width: 16px;
        height: 16px;
        colorize: FluentTokens.neutral_fg_2;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    accessible-label: root.label;
}
