import { FluentTokens } from "../../theme/fluent-tokens.slint";

export component NavButton inherits Rectangle {
    in property <length> btn_size: 36px;
    in property <image> icon;
    in property <string> tooltip;

    callback clicked();

    width: btn_size;
    height: btn_size;
    border-radius: FluentTokens.border_radius_small;
    background: touch.pressed ? FluentTokens.neutral_bg_1_pressed : touch.has-hover ? FluentTokens.neutral_bg_1_hover : FluentTokens.neutral_bg_1;

    animate background { duration: 150ms; }

    if icon != @image-url(""): Image {
        source: icon;
        width: 16px;
        height: 16px;
        colorize: FluentTokens.neutral_fg_2;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    touch := TouchArea {
        clicked => { root.clicked(); }
        mouse-cursor: pointer;
    }

    accessible-role: button;
    accessible-label: root.tooltip;
}
