import { ThemePalette } from "./theme-palette.slint";

export global DarkPalette {
    out property <ThemePalette> colors: {
        color_neutral_background_1: #1a1a1a,
        color_neutral_background_1_hover: #242424,
        color_neutral_background_1_pressed: #333333,
        color_neutral_background_2: #1f1f1f,
        color_neutral_background_3: #292929,
        color_neutral_background_4: #333333,
        color_neutral_background_5: #252525,
        color_neutral_background_inverted: #ffffff,

        color_neutral_foreground_1: #ffffff,
        color_neutral_foreground_2: #e0e0e0,
        color_neutral_foreground_3: #adadad,
        color_neutral_foreground_4: #949494,
        color_neutral_foreground_inverted: #242424,
        color_neutral_foreground_on_brand: #ffffff,

        color_neutral_stroke_1: #525252,
        color_neutral_stroke_1_hover: #616161,
        color_neutral_stroke_1_pressed: #707070,
        color_neutral_stroke_2: #3d3d3d,
        color_neutral_stroke_disabled: #424242,

        color_status_success: #54b054,
        color_status_warning: #fce100,
        color_status_danger: #ff99a4,
        color_status_info: #62abf5,

        color_overlay: #000000CC,
        color_shadow_ambient: rgba(0, 0, 0, 0.24),
        color_shadow_key: rgba(0, 0, 0, 0.28),

        color_stencil_1: #1e1e1e,
        color_stencil_2: #2d2d2d,
        color_stencil_3: #3c3c3c,

        // Brand
        brand_bg_options: [
            #0078D4, #0099BC, #7A7574, #767676,
            #FF8C00, #E81123, #0063B1, #6B69D6,
            #038387, #00B294, #C239B3, #9A0089
        ],
    };
}
