import { ThemePalette } from "./theme-palette.slint";

export global LightPalette {
    out property <ThemePalette> colors: {
        color_neutral_background_1: #ffffff,
        color_neutral_background_1_hover: #f5f5f5,
        color_neutral_background_1_pressed: #e0e0e0,
        color_neutral_background_2: #fafafa,
        color_neutral_background_3: #f0f0f0,
        color_neutral_background_4: #e8e8e8,
        color_neutral_background_5: #f5f5f5,
        color_neutral_background_inverted: #242424,

        color_neutral_foreground_1: #242424,
        color_neutral_foreground_2: #424242,
        color_neutral_foreground_3: #616161,
        color_neutral_foreground_4: #707070,
        color_neutral_foreground_inverted: #ffffff,
        color_neutral_foreground_on_brand: #ffffff,

        color_neutral_stroke_1: #d1d1d1,
        color_neutral_stroke_1_hover: #c7c7c7,
        color_neutral_stroke_1_pressed: #b3b3b3,
        color_neutral_stroke_2: #e0e0e0,
        color_neutral_stroke_disabled: #e0e0e0,

        color_status_success: #0e700e,
        color_status_warning: #dcb20b,
        color_status_danger: #c4314b,
        color_status_info: #0f6cbd,

        color_overlay: #00000088,
        color_shadow_ambient: rgba(0, 0, 0, 0.12),
        color_shadow_key: rgba(0, 0, 0, 0.14),

        color_stencil_1: #ffffff,
        color_stencil_2: #f9f9f9,
        color_stencil_3: #f3f3f3,

        // Brand
        brand_bg_options: [
            #0078D4, #0099BC, #7A7574, #767676,
            #FF8C00, #E81123, #0063B1, #6B69D6,
            #038387, #00B294, #C239B3, #9A0089
        ],
    };
}
