export struct ThemePalette {
    // Neutral Background
    color_neutral_background_1: color,
    color_neutral_background_1_hover: color,
    color_neutral_background_1_pressed: color,
    color_neutral_background_2: color,
    color_neutral_background_3: color,
    color_neutral_background_4: color,
    color_neutral_background_5: color,
    color_neutral_background_inverted: color,

    // Neutral Foreground
    color_neutral_foreground_1: color,
    color_neutral_foreground_2: color,
    color_neutral_foreground_3: color,
    color_neutral_foreground_4: color,
    color_neutral_foreground_inverted: color,
    color_neutral_foreground_on_brand: color,

    // Neutral Stroke
    color_neutral_stroke_1: color,
    color_neutral_stroke_1_hover: color,
    color_neutral_stroke_1_pressed: color,
    color_neutral_stroke_2: color,
    color_neutral_stroke_disabled: color,

    // Status
    color_status_success: color,
    color_status_warning: color,
    color_status_danger: color,
    color_status_info: color,

    // Overlay & Shadow
    color_overlay: color,
    color_shadow_ambient: color,
    color_shadow_key: color,

    // Stencil
    color_stencil_1: color,
    color_stencil_2: color,
    color_stencil_3: color,

    // Brand
    brand_bg_options: [color],
}
